apiVersion: v1
kind: Pod
metadata:
  name: builder
  namespace: default
spec:
  containers:
    - name: pull-test
      image: gcr.io/cloud-builders/docker
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      resources:
        limits:
          memory: "4G"
          cpu: "3500m"
