apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.5-gcs-prometheus"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.5.jar"
  hadoopConf:
    "fs.gs.project.id": "deeplearning-321920"
    "fs.gs.system.bucket": "dmittov-spark"
    "google.cloud.auth.service.account.enable": "true"
    "google.cloud.auth.service.account.json.keyfile": "/mnt/secrets/key.json"
  arguments:
    - "100000"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: spark-operator-spark
    secrets:
      - name: k8s-spark-secret
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: deeplearning-321920
  executor:
    cores: 2
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.5
    secrets:
      - name: k8s-spark-secret
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: deeplearning-321920
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
      port: 8090
