"""init design

Revision ID: 018e4ae2c64f
Revises: b8ae78a2b17f
Create Date: 2023-05-01 14:00:36.758240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018e4ae2c64f'
down_revision = 'b8ae78a2b17f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_index(op.f('ix_artist_artist_id'), 'artist', ['artist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_artist_id'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
