# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    required_providers {
        google = {
            source  = "hashicorp/google"
            version = "~>4.0"
        }

        # Use the latest versions
        kubernetes = {
            source = "hashicorp/kubernetes"
        }
        helm = {
            source = "hashicorp/helm"
        }
    }
}
provider "google" {
    project = "ml-lab-324709"
    region  = "europe-west1"
}
