pg:
  storage: 1Gi
  gke:
    use: false
  backup:
    destination: s3://pg-backup
    type: minio
    action: create

mlflow:
  replicaCount: 1
  backendStore:
    databaseMigration: true
    databaseConnectionCheck: true
    postgres:
      enabled: true
      host: mlflow-rw
      port: 5432
      database: db
      user: pguser
      password: pgpasswd
  artifactRoot:
      proxiedArtifactStorage: true
      # local minio
      s3:
        enabled: true
        bucket: mlflow
        path: /
        awsAccessKeyId: awsAccessKeyId
        awsSecretAccessKey: awsSecretAccessKey
