replicaCount: 1

serviceAccount:
  create: true
  annotations: {
    iam.gke.io/gcp-service-account: mlflow@ml-lab-324709.iam.gserviceaccount.com
  }
  name: "mlflow"

podAnnotations: {}

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: pg-mlflow-rw
    port: 5432 # required
    database: "db"
    user: "pguser"
    password: "password"
    driver: ""

artifactRoot:
  # -- Specifies if you want to enable proxied artifact storage access
  # proxiedArtifactStorage: true
  gcs:
    enabled: true
    bucket: "ml-lab-324709-mlflow" # required
    path: "" # optional

# -- A map of arguments and values to pass to the `mlflow server` command
# Keys must be camelcase. Helm will turn them to kebabcase style.
extraArgs: {}
# Number of gunicorn worker processes to handle requests (default: 4).
  # workers: TEXT
# A prefix which will be prepended to the path of all static paths.
# It must always start with slash `/`
# e.g. /mlflow
  # staticPrefix: TEXT
# Additional command line options forwarded to gunicorn processes.
  # gunicornOpts: TEXT
# Additional command line options for waitress-serve.
  # waitressOpts: TEXT

# -- A list of flags to pass to `mlflow server` command
# Items must be camelcase. Helm will turn them to kebabcase style.
extraFlags: []
# If specified, enables serving of artifact uploads, downloads, and list requests by routing these requests
# to the storage location that is specified by ‘–artifact-destination’ directly through a proxy.
  # serveArtifacts
# If specified, configures the mlflow server to be used only for proxied artifact serving.
  # artifactsOnly

# -- Extra environment variables
extraEnvVars: {}
  # MLFLOW_S3_IGNORE_TLS: true
  # MLFLOW_S3_UPLOAD_EXTRA_ARGS: '{"ServerSideEncryption": "aws:kms", "SSEKMSKeyId": "1234"}'
  # AWS_DEFAULT_REGION: my_region
  # MLFLOW_S3_ENDPOINT_URL: http://1.2.3.4:9000
  # AWS_CA_BUNDLE: /some/ca/bundle.pem
  # MLFLOW_GCS_DEFAULT_TIMEOUT - Sets the standard timeout for transfer operations in seconds (Default: 60). Use -1 for indefinite timeout.
  # MLFLOW_GCS_UPLOAD_CHUNK_SIZE - Sets the standard upload chunk size for bigger files in bytes (Default: 104857600 ≙ 100MiB), must be multiple of 256 KB.
  # MLFLOW_GCS_DOWNLOAD_CHUNK_SIZE - Sets the standard download chunk size for bigger files in bytes (Default: 104857600 ≙ 100MiB), must be multiple of 256 K

# -- Extra secrets for environment variables
extraSecretNamesForEnvFrom: []
# - my-mlflow-secrets

ingress:
  # -- Specifies if you want to create an ingress access
  enabled: false
  # -- New style ingress class name. Only possible if you use K8s 1.18.0 or later version
  className: ""
  # -- Additional ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          # -- Ingress path type
          pathType: ImplementationSpecific
  # -- Ingress tls configuration for https access
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Set the resources requests and limits
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

serviceMonitor:
  # -- When set true then use a ServiceMonitor to configure scraping
  enabled: false
  # -- When set true then use a service port. On default use a pod port.
  useServicePort: false
  # -- Set the namespace the ServiceMonitor should be deployed
  namespace: monitoring
  # -- Set how frequently Prometheus should scrape
  interval: 30s
  # -- Set path to mlflow telemtery-path
  telemetryPath: /metrics
  # -- Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  labels:
    # -- default `kube prometheus stack` helm chart serviceMonitor selector label
    # Mostly it's your prometheus helm release name. Please find more information from here:
    # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md#troubleshooting-servicemonitor-changes
    release: prometheus
  # -- Set timeout for scrape
  timeout: 10s
  # -- Set of labels to transfer on the Kubernetes Service onto the target.
  targetLabels: []

  # -- Set of rules to relabel your exist metric labels
  metricRelabelings: []
    # - sourceLabels: [prometheus_replica]
    #   regex: (.*)
    #   targetLabel: another_prometheus_replica
    #   action: replace
    # - regex: prometheus_replica
    #   action: labeldrop

# -- Set the node selector for the pod.
nodeSelector: {}

# -- Set the tolerations for the pod.
tolerations: []

# -- Set the affinity for the pod.
affinity: {}

# -- Init Containers for Mlflow Pod
initContainers: []

# -- Extra containers for the mlflow pod
extraContainers: []

# -- Extra Volumes for the pod
extraVolumes: []
# - name: mlflow-volume
#   persistentVolumeClaim:
#     claimName: mlflow-pv-volume
# - name: example
#   configMap:
#     name: example

# -- Extra Volume Mounts for the mlflow container
extraVolumeMounts: []
# - name: mlflow-volume
#   mountPath: /mlflow/data
# - name: example
#   mountPath: /example

# -- Liveness probe configurations. Please look to [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes).
livenessProbe: {}
  # initialDelaySeconds: 0
  # periodSeconds: 10
  # timeoutSeconds: 1
  # failureThreshold: 3

# -- Readiness probe configurations. Please look to [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes).
readinessProbe: {}
  # initialDelaySeconds: 0
  # periodSeconds: 10
  # timeoutSeconds: 1
  # failureThreshold: 3
