apiVersion: batch/v1
kind: Job
metadata:
  name: ms-celeb-1m-downloader
spec:
  template:
    spec:
      containers:
        - name: downloader
          image: gcr.io/ml-lab-324709/aria2
          command: ["/bin/bash"]
          args:
            - -c
            - >-
              aria2c --seed-time=0 --enable-dht=false --dir=/data "magnet:?xt=urn:btih:9e67eb7cc23c9417f39778a8e06cca5e26196a97&tr=https%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969" &&
              gsutil -m cp -r /data/* gs://ml-lab-324709-datasets
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "750m"
      volumes:
        - name: data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 300Gi
      restartPolicy: Never
