apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-ms-celeb-1m
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ms-celeb-1m-downloader
spec:
  template:
    spec:
      containers:
        - name: downloader
          image: gcr.io/ml-lab-324709/aria2
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 3600; done;"]
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "3900m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-ms-celeb-1m
      restartPolicy: Never
